#pragma once

namespace ex8 {
/*
 * Sets the initial value of the first element of a linear congruent oscillator
 * sequence.
 */
void set_seed(unsigned long int seed);

/*
 * Returns the maximum possible number that can be generated by the randint()
 * function.
 */
unsigned long maxrand();

/*
 * Generates a random number using a linear congruent generator.
 * The first member of the sequence is set by set_seed(), this member defaults
 * to 1. Each time randint() is called, the generated number is stored in an
 * internal variable and used in the next randint() call.
 */
int randint();

/*
 * Calls randint() to generate a random number, then casts it to the range [a,
 * b).
 */
int rand_in_range(int a, int b);
}  // namespace ex8